
<!DOCTYPE html>
<html>

    <head>
        <title>Secret Server Coding Task</title>
        <link rel="stylesheet" href="/public/css/style.css">
    </head>

    <body>
        <h1>Secret Server Task</h1>

        <p>This is an API server of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certain number of views or after a certain period of time.</p>

        <h2>POST /secret</h2>
        <p>Add a new secret</p>

        <h2>GET /secret/{hash}</h2>
        <p>Find a secret by hash</p>
    </body>

</html>
