<!DOCTYPE html>
<html>

    <head>
        <title>Secret Server Coding Task</title>
        <link rel="stylesheet" href="/public/css/style.css">
    </head>

    <body>
        <h1>Secret Server Task</h1>

        <p>This is an API server of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certain number of views or after a certain period of time.</p>

        <h2>Endpoints</h2>
        <h3>POST /secret</h3>
        <p>Add a new secret</p>

        <h3>GET /secret/{hash}</h3>
        <p>Find a secret by hash</p>

        <h2>How to setup</h2>
        <p>To build and start: <code>bash manage.sh start</code></p>
        <p>Then you need to initialize the database:</p>
        <p><code>bash manage.sh enter db</code></p>
        <p><code>bash migrations/migrate.sh 0000</code></p>
        <p>You can use <code>reset</code> instead of <code>0000</code> to start again with an empty database.</p>
    </body>

</html>
